#           o   o 
#                         /^^^^^7
#           '  '     ,oO))))))))Oo,
#                  ,'))))))))))))))), /{
#             '  ,'o  ))))))))))))))))={
#                >    ))))))))))))))))={        Starting!
#                `,   ))))))\ \)))))))={   
#                  ',))))))))\/)))))' \{
#                    '*O))))))))O*'
Sys.time()
### Master Script ###

#This runs each .R script in turn

# Read the PBKinput dataframe
PBKinput <- read.csv("PBKinput.csv")

# Read the template script
template_script <- readLines("PBK Model v10.R")  # Adjust the path to your template

# Iterate over each name in column A
for (name in PBKinput$Name) {
  # Replace the target_name in the template with the current name
  new_script <- gsub('target_name <- "Example"', paste('target_name <- "', name, '"', sep = ""), template_script)
  
  # Create a new filename for the modified script
  new_filename <- paste0(name, ".R")  # Save with the name as part of the filename
  
  # Write the modified script to a new file
  writeLines(new_script, new_filename)
}


source("P01Disulfiram.R")
source("P02Felbinac.R")
source("P03Flecainide.R")
source("P04Orphenadrine.R")
source("P05Prazosin.R")
source("P06Sulpiride.R")
source("P07Tribenoside.R")
source("P08Bimatoprost.R")
source("P09Ataluren.R")
source("P10Procyclidine.R")
source("P11Clomethiazole.R")
source("P12Nimesulide.R")
source("P13Tolperisone.R")
source("P14Cilostazol.R")
source("P15Mephenoxalone.R")
source("P16Heptaminol.R")
source("P17Indomethacin.R")
source("P18Clozapine.R")
source("P19Tolbutamide.R")
source("P20Indapamide.R")
source("P21Perazine.R")
source("P22Fluphenazine.R")
source("P23Ketoconazole.R")
source("P24Imiquimod.R")
source("P25Quetiapine.R")
source("1Carbamazepine.R")
source("2Carbamazepine.R")
source("3Carbamazepine.R")
source("4Diclofenac.R")
source("5Diclofenac.R")
source("6Diclofenac.R")
source("7Diltiazem.R")
source("8Haloperidol.R")
source("9Ibuprofen.R")
source("10Ibuprofen.R")
source("11Ibuprofen.R")
source("12Ketoprofen.R")
source("13Ketoprofen.R")
source("14Ketoprofen.R")
source("15Levonorgestrel.R")
source("16Memantine.R")
source("17Naproxen.R")
source("18Naproxen.R")
source("19Naproxen.R")
source("20Orphenadrine.R")
source("21Oxazepam.R")
source("22Oxazepam.R")
source("23Oxazepam.R")
source("24Sertraline.R")
source("25Tramadol.R")
source("26Tramadol.R")
source("27Tramadol.R")
source("28Verapamil.R")
source("29Ibuprofen.R")
source("30Naproxen.R")
source("31Diclofenac.R")
source("32Gemfibrozil.R")
source("33Erythromycin.R")
source("34Erythromycin.R")
source("35Erythromycin.R")
source("36Erythromycin.R")
source("37Erythromycin.R")
source("38Erythromycin.R")
source("39Sulfamethazine.R")
source("40Valsartan.R")
source("41Diphenhydramine.R")
source("42Diphenhydramine.R")
source("43Diphenhydramine.R")
source("44Diphenhydramine.R")
source("45Benztropine.R")
source("46Iopamidol.R")
source("47Iopamidol.R")
source("48Iopamidol.R")
source("49Iopamidol.R")
source("50Caffeine.R")
source("51Caffeine.R")
source("52Caffeine.R")
source("53Caffeine.R")
source("54Caffeine.R")
source("55Gemfibrozil.R")
source("56Gemfibrozil.R")
source("57Gemfibrozil.R")
source("58Gemfibrozil.R")
source("59Gemfibrozil.R")
source("60Ibuprofen.R")
source("61Diazepam.R")
source("62Diazepam.R")
source("63Diazepam.R")
source("64Diazepam.R")
source("65Diazepam.R")
source("66Venlafaxine.R")
source("67Venlafaxine.R")
source("68Venlafaxine.R")
source("69Venlafaxine.R")
source("70Venlafaxine.R")
source("71Citalopram.R")
source("72Citalopram.R")
source("73Citalopram.R")
source("74Citalopram.R")
source("75Fluoxetine.R")
source("76Fluoxetine.R")
source("77Fluoxetine.R")
source("78Fluoxetine.R")
source("79Fluoxetine.R")
source("80Amitriptyline.R")
source("81Amitriptyline.R")
source("82Amitriptyline.R")
source("83Amitriptyline.R")
source("84Amitriptyline.R")
source("85Sertraline.R")
source("86Sertraline.R")
source("87Sertraline.R")
source("88Sertraline.R")
source("89Sertraline.R")
source("90Diclofenac.R")
source("91Diclofenac.R")
source("92Diclofenac.R")
source("93Diclofenac.R")
source("94Indomethacin.R")
source("95Indomethacin.R")
source("96Indomethacin.R")
source("97Indomethacin.R")
source("98Mefenamic acid.R")
source("99Mefenamic acid.R")
source("100Mefenamic acid.R")
source("101Mefenamic acid.R")
source("102Bezafibrate.R")
source("103Sertraline.R")
source("104Sertraline.R")
source("105Sertraline.R")
source("106Sertraline.R")
source("107Diphenhydramine.R")
source("108Diphenhydramine.R")
source("109Diphenhydramine.R")
source("110Diphenhydramine.R")
source("111Carbamazepine.R")
source("112Carbamazepine.R")
source("113Carbamazepine.R")
source("114Carbamazepine.R")
source("115Haloperidol.R")
source("116Haloperidol.R")
source("117Haloperidol.R")
source("118Haloperidol.R")
source("119Crotamiton.R")
source("120Crotamiton.R")
source("121Crotamiton.R")
source("122Diltiazem.R")
source("123Diltiazem.R")
source("124Diltiazem.R")
source("125Diltiazem.R")
source("126Triclosan.R")
source("127Triclosan.R")
source("128Triclosan.R")
source("129Triclosan.R")
source("130Temazepam.R")
source("131Methocarbamol.R")
source("132Rosuvastatin.R")
source("133Diltiazem.R")
source("134Carbamazepine.R")
source("135Diphenhydramine.R")
source("136Ibuprofen.R")
source("137Fluoxetine.R")
source("138Fluoxetine.R")
source("139Fluoxetine.R")
source("140Fluoxetine.R")
source("141Diazepam.R")
source("142Azithromycin.R")
source("143Nicotine.R")
source("144Prednisolone.R")
source("145Procainamide.R")
source("146Cimetidine.R")
source("147Caffeine.R")
source("148Dexamethasone.R")
source("149Lacosamide.R")
source("150Acetaminophen.R")
source("151Phenobarbital.R")
source("152CBD Cannabidiol.R")
source("153Prednisone.R")
source("154Rufinamide.R")
source("155Propoxyphene.R")
source("156Gabapentin.R")
source("157Methylphenidate.R")
source("158Trimethoprim.R")
source("159Naproxen.R")
source("160Norfloxacin.R")
source("161Phenylephrine.R")
source("162Pregabalin.R")
source("163Pseudoephedrine.R")
source("164Simvastatin.R")
source("165Sulfadiazine.R")
source("166Metformin.R")
source("167Dextromethorphan.R")
source("168Cetirizine.R")
source("169Carbamazepine.R")
source("170Amphetamine.R")
source("171Citalopram.R")
source("172Omeprazole.R")
source("173Phenytoin.R")
source("174THC delta9-Tetrahydrocannabinol.R")
source("175Loratadine.R")
source("176Penicillin V.R")
source("177Naloxone.R")
source("178Topiramate.R")
source("179Naproxen.R")
source("180Naproxen.R")
source("181Ibuprofen.R")
source("182Ibuprofen.R")
source("183Diclofenac.R")
source("184Diclofenac.R")
source("185Gemfibrozil.R")
source("186Gemfibrozil.R")
source("187Risperidone.R")
source("188Risperidone.R")
source("189Diphenhydramine.R")
source("190Diphenhydramine.R")
source("191Fluoxetine.R")
source("192Fluoxetine.R")
source("193Sertraline.R")
source("194Sertraline.R")
source("195Carbamazepine.R")
source("196Carbamazepine.R")
source("197Diclofenac.R")
source("198Diclofenac.R")
source("199Naproxen.R")
source("200Naproxen.R")
source("201Ibuprofen.R")
source("202Ibuprofen.R")
source("203Carbamazepine.R")
source("204Carbamazepine.R")
source("205Bisoprolol.R")
source("206Diclofenac.R")
source("207Diclofenac.R")
source("208Diclofenac.R")
source("209Diclofenac.R")
source("210Diclofenac.R")
source("211Diclofenac.R")
source("212Diclofenac.R")
source("213Caffeine.R")
source("214Citalopram.R")
source("215Diphenhydramine.R")
source("216Erythromycin.R")
source("217Furosemide.R")
source("218Gemfibrozil.R")
source("219Hydrochlorothiazide.R")
source("220Ibuprofen.R")
source("221Metformin.R")
source("222Sertraline.R")
source("223Theophylline.R")
source("224Thiabendazole.R")
source("225Ibuprofen.R")
source("226Ibuprofen.R")
source("227Ibuprofen.R")
source("228Ibuprofen.R")
source("229Ibuprofen.R")
source("230Ibuprofen.R")
source("231Ibuprofen.R")
source("232Diphenhydramine.R")
source("233Diphenhydramine.R")
source("234Diphenhydramine.R")
source("235Venlafaxine.R")
source("236Temazepam.R")
source("240Diclofenac.R")
source("241Carbamazepine.R")
source("242Fluoxetine.R")
source("243Sertraline.R")
source("244Fluoxetine.R")
source("245Venlafaxine.R")
source("246Venlafaxine.R")
source("247Carbamazepine.R")
source("248Carbamazepine.R")
source("249Carbamazepine.R")
source("250Carbamazepine.R")
source("251Propranolol.R")
source("252Propranolol.R")
source("253Propranolol.R")
source("254Propranolol.R")
source("255Propranolol.R")
source("256Propranolol.R")
source("257Propranolol.R")
source("258Propranolol.R")
source("259Propranolol.R")
source("260Propranolol.R")
source("261Propranolol.R")
source("262Propranolol.R")
source("263Propranolol.R")
source("264Carbamazepine.R")
source("265Diltiazem.R")
source("266Diltiazem.R")
source("267Ketoprofen.R")
source("268Ketoprofen.R")
source("269Ketoprofen.R")
source("270Gemfibrozil.R")
source("271Gemfibrozil.R")
source("272Beclomethasone dipropionate.R")
source("273Beclomethasone dipropionate.R")
source("274Norethindrone.R")
source("275Verapamil.R")
source("276Clozapine.R")
source("277Medroxyprogesterone acetate.R")
source("RC1Carbamazepine.R")
source("RC2Carbamazepine.R")
source("RC3Diclofenac.R")
source("RC4Diclofenac.R")
source("RC5Diphenhydramine.R")
source("RC6Fluoxetine.R")




### Writing all blood concentrations to an excel file ###

# List all CSV files in the directory
files <- list.files(pattern = "\\.csv$")

# Create an empty data frame to store results
result <- data.frame(FileName = character(), C_ven = numeric(), C_art = numeric(), stringsAsFactors = FALSE)

# Loop through each file
for (file in files) {
  # Read the CSV file
  data <- read.csv(file, header = TRUE, stringsAsFactors = FALSE)
  
  # Check if the data has rows and the required columns before extracting values
  if (nrow(data) > 0 && all(c("C_ven", "C_art") %in% colnames(data))) {
    # Extract values
    B_value <- data[nrow(data), "C_ven"]
    C_value <- data[nrow(data), "C_art"]
  } else {
    # Set default values if conditions are not met
    B_value <- NA
    C_value <- NA
  }
  
  # Add the file name, C_ven, and C_art values to the result data frame
  result <- rbind(result, data.frame(FileName = file, C_ven = B_value, C_art = C_value, stringsAsFactors = FALSE))
}

# Write the result to a new Excel file using writexl
library(writexl)
write_xlsx(result, "combined_plasma_results.xlsx")

endtime <- Sys.time()

#           o   o 
#                         /^^^^^7
#           '  '     ,oO))))))))Oo,
#                  ,'))))))))))))))), /{
#             '  ,'^  ))))))))))))))))={
#                >    ))))))))))))))))={           Done!
#                `,   ))))))\ \)))))))={   
#                  ',))))))))\/)))))' \{
#                    '*O))))))))O*'